services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: insightvault-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: insightvault
      POSTGRES_USER: insightvault
      POSTGRES_PASSWORD: insightvault

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: insightvault-backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    depends_on:
      - postgres

volumes:
  postgres_data: